### ISSUE TITLE
Multiple ISBNs in mongo / validation failure

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSimportpipeline#101]
I see repeated errors in the ADSImportpipeline logs:
```
ERROR   780 [07/13/2015 09:48:28]:      2001ASSL..263..107O: Traceback (most recent call last):
  File "/proj.adsx/ADSimportpipeline/pipeline/workers.py", line 100, in on_message
    result = json.dumps(self.strategies[producer]([content]))
  File "/proj.adsx/ADSimportpipeline/pipeline/../lib/SolrUpdater.py", line 717, in solrUpdate
    SolrAdapter.validate(r) #Raises AssertionError if not validated
  File "/proj.adsx/ADSimportpipeline/pipeline/../lib/SolrUpdater.py", line 611, in validate
    assert len(set([type(i) for i in v])) == 1, "%s: multiple data-types in a list" % k
AssertionError: isbn: multiple data-types in a list
```
The problem is apparent in the mongo document:
```
			"isbns" : [
				{
					"origin" : "ADS",
					"content" : "0792370503"
				},
				{
					"origin" : "ADS",
					"content" : [
						"0792370503",
						"0-7923-7050-3"
					]
				}
```
But I don't see this data coming from ADSExports.  So are these stale records which cause the ingest to repeatedly fail?

**Comment by vsudilov** [comment]
yes; the modtime for this record is `2014-12-09T19:02:42.971730Z`. We only saw this because we asked for a full ingest.

Everything is OK from my perspective; when/if the fingerprint changes it will be updated. We can always re-build the entire mongo from scratch too, but that probably shouldn't be done for the benefit of a tiny fraction of "bad" records -- especially not before the IAU.

Please close if you're on the same page.

**Comment by aaccomazzi** [comment]
Can't we reingest these by hand?  I'll create the list

**Comment by vsudilov** [comment]
sure.
